# Pandas

In [1]:
import pandas as pd
import numpy as np

In [2]:
my_series = pd.Series([1,3,5,np.nan,6,8])
my_series

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [3]:
my_series2 = pd.Series([1,3,5,np.nan,6,8], 
                       index = ['a', 'z', 'f', 'd', 'q', 't'])

In [4]:
my_series2

a    1.0
z    3.0
f    5.0
d    NaN
q    6.0
t    8.0
dtype: float64

In [5]:
my_series2[2]

5.0

In [6]:
my_series.values

array([ 1.,  3.,  5., nan,  6.,  8.])

In [9]:
my_series >= 5

0    False
1    False
2     True
3     True
4     True
5     True
dtype: bool

In [8]:
my_series[3] = np.inf

In [10]:
my_series[my_series >= 5]

2    5.0
3    inf
4    6.0
5    8.0
dtype: float64

In [11]:
my_dates_index = pd.date_range('20210513', periods=6)

In [12]:
my_dates_index

DatetimeIndex(['2021-05-13', '2021-05-14', '2021-05-15', '2021-05-16',
               '2021-05-17', '2021-05-18'],
              dtype='datetime64[ns]', freq='D')

In [14]:
my_series.index = my_dates_index

In [15]:
my_series

2021-05-13    1.0
2021-05-14    3.0
2021-05-15    5.0
2021-05-16    inf
2021-05-17    6.0
2021-05-18    8.0
Freq: D, dtype: float64

In [16]:
my_series.mean()

inf

In [17]:
my_series.shape

(6,)

In [19]:
my_series.reshape((2,3))

AttributeError: 'Series' object has no attribute 'reshape'

## Dataframe

In [20]:
sample_np_arr = np.array(np.arange(24)).reshape((6,4)) 

In [21]:
sample_np_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [23]:
sample_df = pd.DataFrame(sample_np_arr, index=my_dates_index,
                        columns=list('ABCD'))

In [25]:
sample_df

A   B   C   D
2021-05-13   0   1   2   3
2021-05-14   4   5   6   7
2021-05-15   8   9  10  11
2021-05-16  12  13  14  15
2021-05-17  16  17  18  19
2021-05-18  20  21  22  23

In [26]:
sample_df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [27]:
sample_df.A

2021-05-13     0
2021-05-14     4
2021-05-15     8
2021-05-16    12
2021-05-17    16
2021-05-18    20
Freq: D, Name: A, dtype: int32

In [29]:
sample_df['A']

2021-05-13     0
2021-05-14     4
2021-05-15     8
2021-05-16    12
2021-05-17    16
2021-05-18    20
Freq: D, Name: A, dtype: int32

In [32]:
sample_df[0:].head(1)

A  B  C  D
2021-05-13  0  1  2  3

In [33]:
sample_df.head()

A   B   C   D
2021-05-13   0   1   2   3
2021-05-14   4   5   6   7
2021-05-15   8   9  10  11
2021-05-16  12  13  14  15
2021-05-17  16  17  18  19

In [34]:
sample_df.tail()

A   B   C   D
2021-05-14   4   5   6   7
2021-05-15   8   9  10  11
2021-05-16  12  13  14  15
2021-05-17  16  17  18  19
2021-05-18  20  21  22  23

In [35]:
sample_df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [36]:
type(sample_df.A)

pandas.core.series.Series

In [37]:
sample_df.describe()

A          B          C          D
count   6.000000   6.000000   6.000000   6.000000
mean   10.000000  11.000000  12.000000  13.000000
std     7.483315   7.483315   7.483315   7.483315
min     0.000000   1.000000   2.000000   3.000000
25%     5.000000   6.000000   7.000000   8.000000
50%    10.000000  11.000000  12.000000  13.000000
75%    15.000000  16.000000  17.000000  18.000000
max    20.000000  21.000000  22.000000  23.000000

In [38]:
sample_df.sort_values(by='D', ascending=False)

A   B   C   D
2021-05-18  20  21  22  23
2021-05-17  16  17  18  19
2021-05-16  12  13  14  15
2021-05-15   8   9  10  11
2021-05-14   4   5   6   7
2021-05-13   0   1   2   3

In [41]:
sample_df.mean()

A    10.0
B    11.0
C    12.0
D    13.0
dtype: float64

In [42]:
sample_df.T

2021-05-13  2021-05-14  2021-05-15  2021-05-16  2021-05-17  2021-05-18
A           0           4           8          12          16          20
B           1           5           9          13          17          21
C           2           6          10          14          18          22
D           3           7          11          15          19          23

In [46]:
sample_df.loc[:'2021-05-14', ['D', 'B']]

D  B
2021-05-13  3  1
2021-05-14  7  5

In [49]:
sample_df[:1]

A  B  C  D
2021-05-13  0  1  2  3

## Zip code

In [63]:
url_base = "http://10.40.6.14/~ehar/sure/data/"
file = 'zips.csv'
url = url_base + file

c = pd.read_csv(url, header=None,
               names = ['i', 'zip', 'state', 'city', 
                        'longitude', 'latitude',
                        'junk1', 'junk2'],
               usecols = ['zip', 'state', 'city', 'longitude',
                         'latitude'],
               dtype = {'zip':str})

In [65]:
c = c.set_index('zip')

In [66]:
c.head()

state        city  longitude   latitude
zip                                          
35004    AL       ACMAR  86.515570  33.584132
35005    AL  ADAMSVILLE  86.959727  33.588437
35006    AL       ADGER  87.167455  33.434277
35007    AL    KEYSTONE  86.812861  33.236868
35010    AL    NEW SITE  85.951086  32.941445

In [62]:
c.zip.values.dtype

dtype('O')

In [68]:
c[c.city == 'PINETTA']

state     city  longitude   latitude
zip                                       
32350    FL  PINETTA  83.340463  30.599703
32350    GA  PINETTA  83.310491  30.634794

In [73]:
c.loc['32350']

state     city  longitude   latitude
zip                                       
32350    FL  PINETTA  83.340463  30.599703
32350    GA  PINETTA  83.310491  30.634794

In [90]:
c.longitude.values.dtype

dtype('float64')

### Find the cities named Canton

In [103]:
c[c.city == 'CANTON'].state.unique().size

18

### Find the northern most zipcode

In [104]:
c.sort_values('latitude', ascending=False).head(1)

state    city   longitude   latitude
zip                                       
99723    AK  BARROW  156.817409  71.234637

In [105]:
c.loc[c.latitude.idxmax()]

state                AK
city             BARROW
longitude    156.817409
latitude      71.234637
Name: 99723, dtype: object

In [108]:
c[c.latitude == c.latitude.max()]

state    city   longitude   latitude
zip                                       
99723    AK  BARROW  156.817409  71.234637

In [112]:
c[c.longitude == c.longitude.min()]

state      city  longitude   latitude
zip                                        
04631    ME  EASTPORT   67.00739  44.919966

In [114]:
c[c.state == 'HI']

state          city   longitude   latitude
zip                                             
96701    HI          AIEA  157.933237  21.390795
96704    HI  CAPTAIN COOK  155.887463  19.438604
96705    HI        ELEELE  159.538115  21.923017
96706    HI     EWA BEACH  158.010307  21.327418
96707    HI       KAPOLEI  158.087007  21.345284
...     ...           ...         ...        ...
96819    HI      HONOLULU  157.875947  21.348770
96821    HI      HONOLULU  157.755242  21.292811
96822    HI      HONOLULU  157.829819  21.311704
96825    HI      HONOLULU  157.698523  21.298684
96826    HI      HONOLULU  157.828388  21.294139

[80 rows x 4 columns]

### Average speed of unladen swallow

In [85]:
bird_speed = pd.read_csv(url_base + 'swallow-speeds.txt',
                        header = None)

### GDP

In [115]:
file = 'gdp_per_capita.csv'

# Sort the table by GDP (and make sure table 
# is updated permanently)

# What should we use as an index?

In [123]:
gdp_per_capita = pd.read_csv(url_base+file, delimiter='\t',
                            encoding='latin1',
                            na_values='n/a',
                            thousands=',')

In [125]:
gdp_per_capita[gdp_per_capita['2015'] == gdp_per_capita['2015'].min()]

Country                                 Subject Descriptor  \
152  South Sudan  Gross domestic product per capita, current prices   

            Units  Scale                      Country/Series-specific Notes  \
152  U.S. dollars  Units  See notes for:  Gross domestic product, curren...   

       2015  Estimates Start After  
152  220.86                 2008.0

In [127]:
gdp_per_capita = gdp_per_capita.set_index('Country')

In [128]:
gdp_per_capita

Subject Descriptor  \
Country                                                                                                 
Afghanistan                                         Gross domestic product per capita, current prices   
Albania                                             Gross domestic product per capita, current prices   
Algeria                                             Gross domestic product per capita, current prices   
Angola                                              Gross domestic product per capita, current prices   
Antigua and Barbuda                                 Gross domestic product per capita, current prices   
...                                                                                               ...   
Vietnam                                             Gross domestic product per capita, current prices   
Yemen                                               Gross domestic product per capita, current prices   
Zambia                                              Gross domestic product per capita, current prices   
Zimbabwe                                            Gross domestic product per capita, current prices   
International Monetary Fund, World Economic Out...                                                NaN   

                                                           Units  Scale  \
Country                                                                   
Afghanistan                                         U.S. dollars  Units   
Albania                                             U.S. dollars  Units   
Algeria                                             U.S. dollars  Units   
Angola                                              U.S. dollars  Units   
Antigua and Barbuda                                 U.S. dollars  Units   
...                                                          ...    ...   
Vietnam                                             U.S. dollars  Units   
Yemen                                               U.S. dollars  Units   
Zambia                                              U.S. dollars  Units   
Zimbabwe                                            U.S. dollars  Units   
International Monetary Fund, World Economic Out...           NaN    NaN   

                                                                        Country/Series-specific Notes  \
Country                                                                                                 
Afghanistan                                         See notes for:  Gross domestic product, curren...   
Albania                                             See notes for:  Gross domestic product, curren...   
Algeria                                             See notes for:  Gross domestic product, curren...   
Angola                                              See notes for:  Gross domestic product, curren...   
Antigua and Barbuda                                 See notes for:  Gross domestic product, curren...   
...                                                                                               ...   
Vietnam                                             See notes for:  Gross domestic product, curren...   
Yemen                                               See notes for:  Gross domestic product, curren...   
Zambia                                              See notes for:  Gross domestic product, curren...   
Zimbabwe                                            See notes for:  Gross domestic product, curren...   
International Monetary Fund, World Economic Out...                                                NaN   

                                                         2015  \
Country                                                         
Afghanistan                                           599.994   
Albania                                              3995.383   
Algeria                                              4318.135   
Angola                                            

In [130]:
gdp_per_capita.sort_values('2015').tail(1)

Subject Descriptor Units  \
Country                                                                       
International Monetary Fund, World Economic Out...                NaN   NaN   

                                                   Scale  \
Country                                                    
International Monetary Fund, World Economic Out...   NaN   

                                                   Country/Series-specific Notes  \
Country                                                                            
International Monetary Fund, World Economic Out...                           NaN   

                                                    2015  \
Country                                                    
International Monetary Fund, World Economic Out...   NaN   

                                                    Estimates Start After  
Country                                                                    
International Monetary Fund, World Economic Out...                    NaN